-- Sign After Six Mobile Notary
-- Run in a new Supabase project's SQL editor.
-- Guest requests should be created through the create-request Edge Function,
-- never by granting public INSERT access directly to these tables.

create extension if not exists pgcrypto;

create type public.request_status as enum (
  'pending','revised_quote','approved','awaiting_payment','confirmed','completed','declined','expired','cancel_requested','reschedule_requested','cancelled'
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users a where a.user_id = auth.uid());
$$;

create table if not exists public.appointment_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status public.request_status not null default 'pending',
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  preferred_contact text,
  referral text,
  appointment_at timestamptz not null,
  backup_time text,
  service_address text not null,
  service_unit text,
  service_zip text,
  location_notes text,
  emergency_opening boolean not null default false,
  one_way_miles numeric(7,2),
  one_way_travel_seconds integer,
  duration_minutes integer not null default 30,
  document_type text not null,
  notarial_act text not null,
  signer_count integer,
  act_count integer,
  acts_unknown boolean not null default false,
  needs_witnesses boolean not null default false,
  document_notes text,
  customer_comments text,
  accommodations jsonb not null default '[]'::jsonb,
  extras jsonb not null default '{}'::jsonb,
  quote_breakdown jsonb not null default '[]'::jsonb,
  quote_total numeric(10,2) not null,
  quote_version integer not null default 1,
  revised_quote_expires_at timestamptz,
  acceptance_token_hash text,
  payment_due_at timestamptz,
  square_payment_link_id text,
  square_payment_link_url text,
  square_order_id text,
  square_payment_id text,
  payment_status text not null default 'unpaid',
  admin_comments text,
  pending_calendar_event_id text,
  confirmed_calendar_event_id text,
  expires_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.request_documents (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.appointment_requests(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text not null,
  byte_size bigint not null,
  locked boolean not null default false,
  delete_after timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.request_management_links (
  request_id uuid primary key references public.appointment_requests(id) on delete cascade,
  management_token text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_revisions (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.appointment_requests(id) on delete cascade,
  version integer not null,
  previous_total numeric(10,2) not null,
  revised_total numeric(10,2) not null,
  breakdown jsonb not null,
  customer_acceptance_required boolean not null,
  accepted_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.availability_blocks (
  id uuid primary key default gen_random_uuid(),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  source text not null default 'manual',
  external_event_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  request_id uuid references public.appointment_requests(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists trg_touch_request on public.appointment_requests;
create trigger trg_touch_request before update on public.appointment_requests for each row execute function public.touch_updated_at();

alter table public.admin_users enable row level security;
alter table public.appointment_requests enable row level security;
alter table public.request_documents enable row level security;
alter table public.request_management_links enable row level security;
alter table public.quote_revisions enable row level security;
alter table public.availability_blocks enable row level security;
alter table public.audit_log enable row level security;

create policy "admins read requests" on public.appointment_requests for select using (public.is_admin());
create policy "admins update requests" on public.appointment_requests for update using (public.is_admin()) with check (public.is_admin());
create policy "customers read own requests" on public.appointment_requests for select using (auth.uid() is not null and user_id=auth.uid());
create policy "admins read docs metadata" on public.request_documents for select using (public.is_admin());
create policy "admins update docs metadata" on public.request_documents for update using (public.is_admin()) with check (public.is_admin());
revoke all on table public.request_management_links from public, anon, authenticated;
create policy "admins manage revisions" on public.quote_revisions for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage blocks" on public.availability_blocks for all using (public.is_admin()) with check (public.is_admin());
create policy "admins read audit" on public.audit_log for select using (public.is_admin());

-- Private storage bucket for uploaded customer documents.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('notary-documents','notary-documents',false,52428800,array['application/pdf','image/jpeg','image/png'])
on conflict (id) do update set public=false;

create policy "admins read private document objects" on storage.objects for select
using (bucket_id='notary-documents' and public.is_admin());

-- Guest upload/write is performed only through Edge Functions with service-role credentials.
-- Add the authenticated Google account to admin_users after first login:
-- insert into public.admin_users(user_id) values ('AUTH-USER-UUID');

-- Lock reviewed files when the request advances beyond pending review, and
-- start the 7-day deletion clock when an appointment is completed.
create or replace function public.request_status_side_effects()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.status in ('approved','awaiting_payment','confirmed','completed') and old.status is distinct from new.status then
    update public.request_documents set locked=true where request_id=new.id;
  end if;
  if new.status='completed' and old.status is distinct from 'completed' then
    new.completed_at=coalesce(new.completed_at,now());
    update public.request_documents set delete_after=coalesce(delete_after,now()+interval '7 days') where request_id=new.id;
  end if;
  return new;
end $$;
drop trigger if exists trg_request_status_side_effects on public.appointment_requests;
create trigger trg_request_status_side_effects before update on public.appointment_requests for each row execute function public.request_status_side_effects();
